const fs=require('fs'),vm=require('vm'),path=require('path');
const ctx={window:{}};vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname,'data.js'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname,'vic-park-players.js'),'utf8'),ctx);
const d=ctx.window.TOURNAMENT_DATA||{}, tracked=ctx.window.VIC_PARK_PLAYERS||[];
const clean=s=>String(s||'').trim().toLowerCase();
const key=s=>{let v=String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’‘]/g,"'").trim();if(v.includes(',')){const p=v.split(',').map(x=>x.trim()).filter(Boolean);if(p.length===2)v=p[1]+' '+p[0];}return v.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().split(/\s+/).filter(Boolean).sort().join(' ')};
const same=(a,b)=>!!a&&!!b&&(clean(a)===clean(b)||key(a)===key(b));
const has=(m,n)=>same(m.player1,n)||same(m.player2,n);
const glass=m=>/\bAGC\b|Karrinyup/i.test([m.court,m.venue,m.rawText].join(' '));
console.log(`Players: ${(d.players||[]).length}`);
console.log(`Matches: ${(d.matches||[]).length}`);
console.log(`Glass Court matches: ${(d.matches||[]).filter(glass).length}`);
console.log(`Last refresh: ${d.refreshedAt||'not recorded'}`);
console.log(`Vic Park players (${tracked.length}):`);
for(const n of tracked) console.log(`  ${n}: ${(d.matches||[]).filter(m=>has(m,n)).length} match(es)`);
